// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: art.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createArt = `-- name: CreateArt :one
INSERT INTO art (name, description, image, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, image, user_id, created_at, updated_at
`

type CreateArtParams struct {
	Name        string
	Description sql.NullString
	Image       sql.NullString
	UserID      uuid.UUID
}

func (q *Queries) CreateArt(ctx context.Context, arg CreateArtParams) (Art, error) {
	row := q.db.QueryRowContext(ctx, createArt,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.UserID,
	)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArt = `-- name: DeleteArt :exec
DELETE FROM art
WHERE id = $1 AND user_id = $2
`

type DeleteArtParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteArt(ctx context.Context, arg DeleteArtParams) error {
	_, err := q.db.ExecContext(ctx, deleteArt, arg.ID, arg.UserID)
	return err
}

const getArtByID = `-- name: GetArtByID :one
SELECT id, name, description, image, user_id, created_at, updated_at FROM art
WHERE id = $1
`

func (q *Queries) GetArtByID(ctx context.Context, id uuid.UUID) (Art, error) {
	row := q.db.QueryRowContext(ctx, getArtByID, id)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtByUser = `-- name: GetArtByUser :many
SELECT id, name, description, image, user_id, created_at, updated_at FROM art
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetArtByUser(ctx context.Context, userID uuid.UUID) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, getArtByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArt = `-- name: ListArt :many
SELECT id, name, description, image, user_id, created_at, updated_at FROM art
ORDER BY created_at DESC
`

func (q *Queries) ListArt(ctx context.Context) ([]Art, error) {
	rows, err := q.db.QueryContext(ctx, listArt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Art
	for rows.Next() {
		var i Art
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArt = `-- name: UpdateArt :one
UPDATE art
SET
    name        = COALESCE($2, name),
    description = COALESCE($3, description),
    image       = COALESCE($3, image),
    updated_at  = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, name, description, image, user_id, created_at, updated_at
`

type UpdateArtParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	UserID      uuid.UUID
}

func (q *Queries) UpdateArt(ctx context.Context, arg UpdateArtParams) (Art, error) {
	row := q.db.QueryRowContext(ctx, updateArt,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var i Art
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
