// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password,
    batch,
    status,
    role
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING 
    id,
    name,
    email,
    batch,
    status,
    role,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
	Batch    sql.NullString
	Status   AccountStatus
	Role     UserRole
}

type CreateUserRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Batch     sql.NullString
	Status    AccountStatus
	Role      UserRole
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Batch,
		arg.Status,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT 
    id,
    name,
    email,
    batch,
    status,
    role,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Batch     sql.NullString
	Status    AccountStatus
	Role      UserRole
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    name,
    email,
    password,
    batch,
    status,
    role,
    created_at,
    updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Batch     sql.NullString
	Status    AccountStatus
	Role      UserRole
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    email = $3,
    password = $4,
    batch = $5,
    status = $6,
    role = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    name,
    email,
    batch,
    status,
    role,
    created_at,
    updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
	Batch    sql.NullString
	Status   AccountStatus
	Role     UserRole
}

type UpdateUserRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Batch     sql.NullString
	Status    AccountStatus
	Role      UserRole
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Batch,
		arg.Status,
		arg.Role,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = $2,
    email = $3,
    batch = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    name,
    email,
    batch,
    status,
    role,
    created_at,
    updated_at
`

type UpdateUserProfileParams struct {
	ID    uuid.UUID
	Name  string
	Email string
	Batch sql.NullString
}

type UpdateUserProfileRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Batch     sql.NullString
	Status    AccountStatus
	Role      UserRole
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Batch,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Batch,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
